# Generated by Django 5.2.8 on 2025-11-22 11:54

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "uuid",
                    models.UUIDField(
                        db_comment="UUID of the model. Meant for access.",
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="When the model was created.")),
                ("updated_at", models.DateTimeField(auto_now=True, db_comment="When the model was last updated.")),
                ("email", models.EmailField(db_comment="THe user's email address", max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, db_comment="The user's first name", max_length=255)),
                ("last_name", models.CharField(blank=True, db_comment="The user's last name", max_length=255)),
                (
                    "is_active",
                    models.BooleanField(db_comment="Whether this user should be treated as active", default=True),
                ),
                (
                    "full_name",
                    models.GeneratedField(
                        db_comment="The user's full name",
                        db_persist=True,
                        expression=django.db.models.functions.text.Trim(
                            django.db.models.functions.text.Concat("first_name", models.Value(" "), "last_name"),
                            output_field=models.TextField(),
                        ),
                        output_field=models.TextField(),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="The user who created the model.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="The user who last updated the model.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
                "ordering": ("-created_at",),
            },
        ),
    ]
