"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from .api import *
from .authentication import *
from .cache import *
from .database import *
from .deployment import *
from .email import *
from .files import *
from .i18n import *
from .installed_apps import *
from .logging import *
from .middleware import *
from .monitoring import *
from .security import *
from .templates import *
from .webserver import *
